In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.naive_bayes import MultinomialNB

### 1. Bag of Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
corpus = [
    'The car is driven on the road',
    'The truck is driven on the highway'
]

In [5]:
# Unigram
vectorizer = CountVectorizer(ngram_range = (1,1))
X = vectorizer.fit_transform(corpus)
print(X.toarray())

[[1 1 0 1 1 1 2 0]
 [0 1 1 1 1 0 2 1]]


In [6]:
vocab = vectorizer.vocabulary_
vocab

{'the': 6,
 'car': 0,
 'is': 3,
 'driven': 1,
 'on': 4,
 'road': 5,
 'truck': 7,
 'highway': 2}

In [7]:
# Bigram
vectorizer = CountVectorizer(ngram_range = (2,2))
X = vectorizer.fit_transform(corpus)
print(X.toarray())

[[1 1 1 1 1 0 1 0 0]
 [0 1 1 1 0 1 0 1 1]]


In [8]:
vocab = vectorizer.vocabulary_
vocab

{'the car': 4,
 'car is': 0,
 'is driven': 2,
 'driven on': 1,
 'on the': 3,
 'the road': 6,
 'the truck': 7,
 'truck is': 8,
 'the highway': 5}

In [9]:
# Unigram + Bigram
vectorizer = CountVectorizer(ngram_range = (1,2))
X = vectorizer.fit_transform(corpus)
print(X.toarray())

[[1 1 1 1 0 1 1 1 1 1 2 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 1 1 0 2 0 1 0 1 1 1]]


In [10]:
vocab = vectorizer.vocabulary_
vocab

{'the': 10,
 'car': 0,
 'is': 5,
 'driven': 2,
 'on': 7,
 'road': 9,
 'the car': 11,
 'car is': 1,
 'is driven': 6,
 'driven on': 3,
 'on the': 8,
 'the road': 13,
 'truck': 15,
 'highway': 4,
 'the truck': 14,
 'truck is': 16,
 'the highway': 12}

### 2. TF - IDF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tvect = TfidfVectorizer()
tfidf = tvect.fit_transform(corpus)
pd.DataFrame(tfidf.toarray())

0        1         2        3        4         5        6         7
0  0.424717  0.30219  0.000000  0.30219  0.30219  0.424717  0.60438  0.000000
1  0.000000  0.30219  0.424717  0.30219  0.30219  0.000000  0.60438  0.424717