In [1]:
import pandas as pd
import numpy as np

### a. Scaling

##### 1. Standardizing

In [2]:
from sklearn.preprocessing import StandardScaler

In [3]:
udf = pd.read_csv("C:/Users/harik/python pratice/00 - datasets-20251216T065029Z-1-001/00 - datasets/Universities.csv", index_col='Univ')
udf.head()

SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ                                                      
Brown     1310     89      22       13     22704        94
CalTech   1415    100      25        6     63575        81
CMU       1260     62      59        9     25026        72
Columbia  1310     76      24       12     31510        88
Cornell   1280     83      33       13     21864        90

In [4]:
# SCaled between -3 and + 3
scaler = StandardScaler()
scaled_data = scaler.fit_transform(udf)
scaled_data

array([[ 0.41028362,  0.6575195 , -0.88986682,  0.07026045, -0.33141256,
         0.82030265],
       [ 1.39925928,  1.23521235, -0.73465749, -1.68625071,  2.56038138,
        -0.64452351],
       [-0.06065717, -0.76045386,  1.02438157, -0.93346022, -0.16712136,
        -1.65863393],
       [ 0.41028362, -0.02520842, -0.78639393, -0.18066972,  0.29164871,
         0.14422904],
       [ 0.12771914,  0.34241431, -0.32076595,  0.07026045, -0.39084607,
         0.36958691],
       [ 0.69284809,  0.6575195 , -0.83813038, -0.68253005,  0.33778044,
         0.93298158],
       [ 0.4573777 ,  0.71003703, -0.47597528, -0.18066972,  0.29695528,
         0.93298158],
       [-0.10775125, -0.13024348, -0.78639393, -0.18066972, -0.51381683,
         0.59494478],
       [ 1.25797704,  0.76255456, -1.30375836, -0.43159988,  0.85874344,
         1.15833946],
       [ 0.36318954, -0.07772595,  0.24833493, -1.43532055,  2.21481798,
         0.0315501 ],
       [ 1.06960072,  0.92010716, -0.47597528, -0.

In [5]:
scaled_df = pd.DataFrame(scaled_data, columns=udf.columns)
scaled_df

SAT     Top10    Accept   SFRatio  Expenses  GradRate
0   0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
1   1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
2  -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
3   0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
4   0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587
5   0.692848  0.657519 -0.838130 -0.682530  0.337780  0.932982
6   0.457378  0.710037 -0.475975 -0.180670  0.296955  0.932982
7  -0.107751 -0.130243 -0.786394 -0.180670 -0.513817  0.594945
8   1.257977  0.762555 -1.303758 -0.431600  0.858743  1.158339
9   0.363190 -0.077726  0.248335 -1.435321  2.214818  0.031550
10  1.069601  0.920107 -0.475975 -0.682530  0.529383  0.482266
11 -0.060657  0.447449 -0.010347 -0.431600  0.046981  0.256908
12 -0.107751  0.237379  0.144862  0.070260 -0.867871  0.820303
13 -1.746625 -2.020875  0.765699  1.324911 -1.217184 -0.757202
14  1.022507  0.762555 -1.303758 -1.184390  0.200376  0.932982
15 -2.462455 -2.546050  2.628211  1.575841 -1.296358 -1.996671
16  0.881224  0.710037 -0.993340 -0.180670  0.641174  0.707624
17 -1.803138 -1.443182  1.438273  3.081422 -1.321971 -2.222029
18 -0.249033  0.972625  0.041389  1.073981 -0.866597 -0.982560
19  0.221907 -0.077726  0.558754  0.070260  0.777730  0.031550
20 -0.814162 -0.602901  1.490010  0.823051 -0.843248 -0.193808
21  0.174813  0.184862 -0.165557 -0.431600  0.011674  0.369587
22 -0.390316  0.027309  0.248335  0.321191 -0.993318  0.594945
23 -1.708950 -1.915840  1.541746  0.572121 -1.098883 -1.771313
24  1.022507  0.972625 -1.045076 -0.431600  1.140982  1.045661

##### 2. Normalizing

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
# Scaled between 0 and 1
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(udf)
scaled_data

array([[0.74390244, 0.84722222, 0.10526316, 0.36842105, 0.25514388,
        0.9       ],
       [1.        , 1.        , 0.14473684, 0.        , 1.        ,
        0.46666667],
       [0.62195122, 0.47222222, 0.59210526, 0.15789474, 0.29746132,
        0.16666667],
       [0.74390244, 0.66666667, 0.13157895, 0.31578947, 0.41562939,
        0.7       ],
       [0.67073171, 0.76388889, 0.25      , 0.36842105, 0.23983525,
        0.76666667],
       [0.81707317, 0.84722222, 0.11842105, 0.21052632, 0.4275118 ,
        0.93333333],
       [0.75609756, 0.86111111, 0.21052632, 0.31578947, 0.41699623,
        0.93333333],
       [0.6097561 , 0.63888889, 0.13157895, 0.31578947, 0.20816096,
        0.83333333],
       [0.96341463, 0.875     , 0.        , 0.26315789, 0.56169926,
        1.        ],
       [0.73170732, 0.65277778, 0.39473684, 0.05263158, 0.91099123,
        0.66666667],
       [0.91463415, 0.91666667, 0.21052632, 0.21052632, 0.47686392,
        0.8       ],
       [0.62195122, 0

In [8]:
scaled_df = pd.DataFrame(scaled_data, columns=udf.columns)
scaled_df

SAT     Top10    Accept   SFRatio  Expenses  GradRate
0   0.743902  0.847222  0.105263  0.368421  0.255144  0.900000
1   1.000000  1.000000  0.144737  0.000000  1.000000  0.466667
2   0.621951  0.472222  0.592105  0.157895  0.297461  0.166667
3   0.743902  0.666667  0.131579  0.315789  0.415629  0.700000
4   0.670732  0.763889  0.250000  0.368421  0.239835  0.766667
5   0.817073  0.847222  0.118421  0.210526  0.427512  0.933333
6   0.756098  0.861111  0.210526  0.315789  0.416996  0.933333
7   0.609756  0.638889  0.131579  0.315789  0.208161  0.833333
8   0.963415  0.875000  0.000000  0.263158  0.561699  1.000000
9   0.731707  0.652778  0.394737  0.052632  0.910991  0.666667
10  0.914634  0.916667  0.210526  0.210526  0.476864  0.800000
11  0.621951  0.791667  0.328947  0.263158  0.352609  0.733333
12  0.609756  0.736111  0.368421  0.368421  0.116965  0.900000
13  0.185366  0.138889  0.526316  0.631579  0.026991  0.433333
14  0.902439  0.875000  0.000000  0.105263  0.392120  0.933333
15  0.000000  0.000000  1.000000  0.684211  0.006597  0.066667
16  0.865854  0.861111  0.078947  0.315789  0.505659  0.866667
17  0.170732  0.291667  0.697368  1.000000  0.000000  0.000000
18  0.573171  0.930556  0.342105  0.578947  0.117293  0.366667
19  0.695122  0.652778  0.473684  0.368421  0.540832  0.666667
20  0.426829  0.513889  0.710526  0.526316  0.123307  0.600000
21  0.682927  0.722222  0.289474  0.263158  0.343515  0.766667
22  0.536585  0.680556  0.394737  0.421053  0.084653  0.833333
23  0.195122  0.166667  0.723684  0.473684  0.057462  0.133333
24  0.902439  0.930556  0.065789  0.263158  0.634397  0.966667

### b. Encoding categorical data

In [9]:
iris = pd.read_csv("C:/Users/harik/python pratice/00 - datasets-20251216T065029Z-1-001/00 - datasets/iris.csv")
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#### a. Label Encoding

In [10]:
iris1 = iris.copy()

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
le.fit_transform(iris1['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
iris1['species'] = le.fit_transform(iris1['species'])
iris1.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

#### b. One Hot Encoding

##### 1. Using OneHotEncoder Class

In [14]:
iris2 = iris.copy()
iris2.head(3)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe = OneHotEncoder()
enc_data = ohe.fit_transform(iris2[['species']])
enc_data

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [17]:
# To display the encoded data
enc_arr = enc_data.toarray()
#enc_arr

In [18]:
iris2.join(pd.DataFrame(enc_arr, columns=['Sp_Setosa','Sp_Versicolor','Sp_Virginica']))

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     Sp_Setosa  Sp_Versicolor  Sp_Virginica  
0          1.0            0.0           0.0  
1          1.0            0.0           0.0  
2          1.0            0.0           0.0  
3          1.0            0.0           0.0  
4          1.0            0.0           0.0  
..         ...            ...           ...  
145        0.0            0.0           1.0  
146        0.0            0.0           1.0  
147        0.0            0.0           1.0  
148        0.0            0.0           1.0  
149        0.0            0.0           1.0  

[150 rows x 8 columns]

In [19]:
final_data = iris2.join(pd.DataFrame(enc_arr, columns=['Sp_Setosa','Sp_Versicolor','Sp_Virginica'])).drop('species', axis=1)
final_data

sepal_length  sepal_width  petal_length  petal_width  Sp_Setosa  \
0             5.1          3.5           1.4          0.2        1.0   
1             4.9          3.0           1.4          0.2        1.0   
2             4.7          3.2           1.3          0.2        1.0   
3             4.6          3.1           1.5          0.2        1.0   
4             5.0          3.6           1.4          0.2        1.0   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3        0.0   
146           6.3          2.5           5.0          1.9        0.0   
147           6.5          3.0           5.2          2.0        0.0   
148           6.2          3.4           5.4          2.3        0.0   
149           5.9          3.0           5.1          1.8        0.0   

     Sp_Versicolor  Sp_Virginica  
0              0.0           0.0  
1              0.0           0.0  
2              0.0           0.0  
3              0.0           0.0  
4              0.0           0.0  
..             ...           ...  
145            0.0           1.0  
146            0.0           1.0  
147            0.0           1.0  
148            0.0           1.0  
149            0.0           1.0  

[150 rows x 7 columns]

#### Drop first

In [20]:
ohe = OneHotEncoder(drop='first')
enc_data = ohe.fit_transform(iris2[['species']])
enc_data.toarray()

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

##### 2. Using get_dummies() from pandas

In [21]:
iris3 = iris.copy()

In [22]:
pd.get_dummies(iris3)

sepal_length  sepal_width  petal_length  petal_width  species_setosa  \
0             5.1          3.5           1.4          0.2            True   
1             4.9          3.0           1.4          0.2            True   
2             4.7          3.2           1.3          0.2            True   
3             4.6          3.1           1.5          0.2            True   
4             5.0          3.6           1.4          0.2            True   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3           False   
146           6.3          2.5           5.0          1.9           False   
147           6.5          3.0           5.2          2.0           False   
148           6.2          3.4           5.4          2.3           False   
149           5.9          3.0           5.1          1.8           False   

     species_versicolor  species_virginica  
0                 False              False  
1                 False              False  
2                 False              False  
3                 False              False  
4                 False              False  
..                  ...                ...  
145               False               True  
146               False               True  
147               False               True  
148               False               True  
149               False               True  

[150 rows x 7 columns]

In [23]:
pd.get_dummies(iris3, drop_first=True)

sepal_length  sepal_width  petal_length  petal_width  species_versicolor  \
0             5.1          3.5           1.4          0.2               False   
1             4.9          3.0           1.4          0.2               False   
2             4.7          3.2           1.3          0.2               False   
3             4.6          3.1           1.5          0.2               False   
4             5.0          3.6           1.4          0.2               False   
..            ...          ...           ...          ...                 ...   
145           6.7          3.0           5.2          2.3               False   
146           6.3          2.5           5.0          1.9               False   
147           6.5          3.0           5.2          2.0               False   
148           6.2          3.4           5.4          2.3               False   
149           5.9          3.0           5.1          1.8               False   

     species_virginica  
0                False  
1                False  
2                False  
3                False  
4                False  
..                 ...  
145               True  
146               True  
147               True  
148               True  
149               True  

[150 rows x 6 columns]