### Probability Calculations

In [1]:
import scipy.stats as st
import numpy as np

#### SAT score follow a normal distribution with mean 711 and std=29

In [2]:
# prob of scoring < 680
p680_less = st.norm.cdf(680, loc=711, scale=29)
np.round(p680_less*100,2)

14.25

In [3]:
# prob of scoring less than< 720
p700_less = st.norm.cdf(720, loc=711, scale=29)
np.round(p700_less*100,2)

62.19

In [4]:
# prob of scoring more than < 720
1 - p700_less 

0.37814937265194704

In [5]:
# prob of scoring between 680 and 720
p700_less - p680_less

0.47930802350923685

#### The annual salaries of employees in a large company are approximately distribution with a mean of $50000 and a stsndard deviation of $10,000


In [6]:
# a) What percent of people earn less than $60,000?
p68k_less =st.norm.cdf(60000, loc=50000, scale=10000)
p68k_less

0.8413447460685429

##### A radar unit is used to measure speeds of cars on a highway. The speeds are normally distributed with a mean of 90 km/hr and a standard deviation of 10 km/hr. 

In [7]:
# What is the probability that a car picked at random is travelling at more than 100 km/hr?
p100_less =st.norm.cdf(100, loc=90, scale=10)
p100_less

0.8413447460685429

In [8]:
# prob of travelling at speed > 100 km/hr
1 - p100_less

0.15865525393145707

##### For a certain type of mobiles, the length of time between charges of the battery is normally distributed with a mean of 10 hours and a standard deviation of 20 minutes. 

In [9]:
# John owns one of these mobiles and wants to know the probability that the length of time will be between 10 and 11 hours.
p600_less =st.norm.cdf(600, loc=600, scale=20)
p600_less

0.5

In [10]:
p660_less =st.norm.cdf(660, loc=600, scale=20)
p660_less

0.9986501019683699

In [11]:
# probability that the length of time will be between 10 and 11 hours.
p660_less - p600_less

0.4986501019683699

### Confidence Interval

In [12]:
cint=st.norm.interval(0.95, loc=1990, scale=2500/np.sqrt(140))
np.round(cint)

array([1576., 2404.])

In [13]:
cint = st.norm.interval(0.90, loc=23.6, scale=7/np.sqrt(100))
np.round(cint,2)

array([22.45, 24.75])

In [14]:
# Using t- dist

In [15]:
cint=st.t.interval(0.95, loc=1990, df=139, scale=2833/np.sqrt(140))
np.round(cint,)

array([1517., 2463.])